controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
auth:
    path: /auth
    methods: ['POST']
swagger_ui:
    path: /docs
    controller: api_platform.swagger.action.ui
stripe:
    path: /create-payment-intent
    controller: App\Controller\StripeController::createPaymentIntent