version: '3'
services:
  api:
    build: api
    ports:
      - 9000:80
    volumes:
      - ../pcs_api:/var/www/html/pcs_api
      - .db/data:/var/www/html/var
      - ./api/conf/.env.local:/var/www/html/pcs_api/.env.local
    networks:
      - symfony
  website:
    build: web
    ports:
      - 9080:80
    volumes:
      - ../appWeb:/var/www/html/appWeb
      - .db/data:/var/www/html/var
      - ./web/conf/.env.local:/var/www/html/appWeb/.env.local
    networks:
      - symfony
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: website
      MYSQL_USER: pcs
      MYSQL_PASSWORD: pass
    ports:
      - 3308:3306
    volumes:
      - .db/data:/var/lib/mysql
    networks:
      - symfony
networks:
  symfony:
    driver: bridge