version: '3.8'
networks:
  symfony:
    driver: bridge
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: website
      MYSQL_USER: pcs
      MYSQL_PASSWORD: pass
    ports:
      - 3308:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - symfony
  api:
    container_name: api
    restart: always
    build: api
    ports:
      - 8004:443
      - 8084:80
    volumes:
      - ../pcs_api:/var/www/html/pcs_api
      # - ./api/conf/.env.local:/var/www/html/pcs_api/.env.local
    networks:
      - symfony
  website:
    container_name: website
    restart: always
    build: web
    ports:
      - 444:443
      - 84:80
    volumes:
      - ../appWeb:/var/www/html/appWeb
      # - ./web/conf/.env.local:/var/www/html/appWeb/.env.local
    networks:
      - symfony
  python:
    container_name: python
    restart: always
    build: 
      context: py
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3004:3004
    volumes:
      - ../appTickets/:/home/docker/
    networks:
      - symfony