version: '3'
services:
  api:
    build:
      context: .
      dockerfile: api.dockerfile
    ports:
      - 8081:80
    volumes:
      - ./pcs_api:/var/www/html
      - .db/data:/var/www/html/var
    networks:
      - symfony
  website:
    build:
      context: .
      dockerfile: website.dockerfile
    ports:
      - 8080:80
    volumes:
      - ./pcs_api:/var/www/html
      - .db/data:/var/www/html/var
    networks:
      - symfony
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pcs
      MYSQL_USER: pcs
      MYSQL_PASSWORD: pcs
    ports:
      - 3306:3306
    volumes:
      - .db/data:/var/lib/mysql
networks:
  symfony:
    driver: bridge