version: '3.8'
networks:
  symfony:
    driver: bridge
services:
  mysql_prod:
    image: mysql:8.0
    container_name: mysql_prod
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: website
      MYSQL_USER: dockerp
      MYSQL_PASSWORD: production
    ports:
      - 3308:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - symfony
  api_prod:
    container_name: api_prod
    restart: on-failure:5 
    build:
      context: api
      dockerfile: Dockerfile
      target: prod
    ports:
      - 8000:443
      - 8080:80
    networks:
      - symfony
  website_prod:
    container_name: website_prod
    restart: on-failure:5 
    build:
      context: web
      dockerfile: Dockerfile
      target: prod
    ports:
      - 443:443
      - 80:80
    networks:
      - symfony
  python_prod:
    container_name: python_prod
    restart: on-failure:5 
    build: 
      context: py
      dockerfile: Dockerfile
      target: prod
    ports:
      - 3000:3000
    networks:
      - symfony